version: '3.4'

services:
  catalogdb:
    image: mongo:5.0.8

  basketdb:
    image: redis:7.0.0-alpine3.16

  discountdb:
    image: postgres:14.3

  portainer:
    image: portainer/portainer-ce:linux-amd64

  pgadmin:
    image: dpage/pgadmin4:6.9

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

  orderdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

  rabbitmq:
    image: rabbitmq:3-management-alpine

  ocelotapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGw/Dockerfile

volumes:
  mongo_data:
  redis_data:
    driver: local
  portainer_data:
  postgres_data:
  pgadmin_data:



